# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Relaciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Relaciones(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 245)
        MainWindow.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 151, 31))
        self.label.setStyleSheet("QLabel{\n"
                                 "    background-color: black;\n"
                                 "    color: #FFFFFF;\n"
                                 "    font: bold 15px;\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "}")
        self.label.setObjectName("label")
        self.inpuLine = QtWidgets.QLineEdit(self.centralwidget)
        self.inpuLine.setGeometry(QtCore.QRect(40, 70, 351, 41))
        self.inpuLine.setStyleSheet("\n"
                                    "    background-color: black;\n"
                                    "    color: #FFFFFF;\n"
                                    "    border-style: double;\n"
                                    "    padding: 2px;\n"
                                    "    font: bold 15px;\n"
                                    "    border-width:2px;\n"
                                    "    border-radius: 10px;\n"
                                    "    border-color: green;")
        self.inpuLine.setObjectName("inpuLine")
        self.outputBox = QtWidgets.QTextEdit(self.centralwidget)
        self.outputBox.setGeometry(QtCore.QRect(470, 20, 231, 171))
        self.outputBox.setStyleSheet("\n"
                                     "    background-color: black;\n"
                                     "    color: #FFFFFF;\n"
                                     "    border-style: double;\n"
                                     "    padding: 2px;\n"
                                     "    font: bold 15px;\n"
                                     "    border-width:2px;\n"
                                     "    border-color: green;")
        self.outputBox.setObjectName("outputBox")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(160, 130, 101, 26))
        self.btnGenerate.setMaximumSize(QtCore.QSize(203, 26))
        self.btnGenerate.setStyleSheet("QPushButton{\n"
                                       "    font: bold 11px;\n"
                                       "    border-style: inset;\n"
                                       "    border-width: 2px;\n"
                                       "    border-color: green;\n"
                                       "    color: #FFFFFF;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton::pressed\n"
                                       "{\n"
                                       "    background-color : green;\n"
                                       "}")
        self.btnGenerate.setObjectName("btnGenerate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Relaciones:"))
        self.btnGenerate.setText(_translate("MainWindow", "Generar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Relaciones()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
